project:
  type: website
  output-dir: docs
  
website:
  title: "webCAT"
  favicon: images/favicon.png
  back-to-top-navigation: true
  page-footer: "Copyright 2025, "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial.qmd
        text: Tutorial
      - href: step4.qmd
        text: Results
      - href: ref.qmd
        text: Reference
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/tasospsy/webCAT
          - text: Report a Bug
            href:  https://github.com/tasospsy/webCAT/issues
  
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-fold: true

    
editor: visual

server:
    port: 8066
